### ISSUE TITLE
Guard for large month to month market increases 

### ISSUE THREAD

**Issue by bigmug** [yegg/s-and-p-timing#1]
During large month to month price increases `$valley` will be set to `$price` at https://github.com/yegg/s-and-p-timing/blob/master/sell_and_hold.pl#L331. If `($price/$series{$starting_date}{'valley'} > $VALLEY_THRESHOLD)` when `$valley` gets set to `$price`, https://github.com/yegg/s-and-p-timing/blob/master/sell_and_hold.pl#L380 will miss the queue to jump in

**Comment by yegg** [comment]
@bigmug finally getting some time to look at this. I think I addressed your point -- thank you for it! -- in https://github.com/yegg/s-and-p-timing/commit/9942fe09e00e3f42223cdae2f507a102d8486600

Can you please review and let me know if you think it is right now?

**Comment by bigmug** [comment]
@yegg nice. I think this fixes it fully 👍
